# Generated by Django 4.1.7 on 2023-04-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_alter_cliente_ci_rif_alter_historicalcliente_ci_rif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorden',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
