# Generated by Django 4.1.7 on 2023-06-20 23:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_cliente_unique_ci_rif_non_deleted_only'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orden',
            managers=[
                ('lista_ordenes', django.db.models.manager.Manager()),
            ],
        ),
    ]
