# Generated by Django 4.1.7 on 2023-07-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_orden_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitemorden',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalorden',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
