# Generated by Django 4.1.7 on 2023-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_historicalorden_pagada_orden_pagada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ci_rif',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
