# Generated by Django 4.1.7 on 2023-04-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3_management', '0001_initial'),
        ('facturacion', '0004_alter_cliente_ci_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notapago',
            name='s3_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='s3_management.s3file'),
        ),
    ]
