# Generated by Django 4.1.7 on 2023-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_historicalitemorden_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factura_offset', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
