# Generated by Django 4.1.7 on 2023-04-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_alter_notapago_s3_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
