# Generated by Django 4.1.7 on 2023-04-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_cliente_email_historicalcliente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfactura',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='recibo_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='s3_file',
        ),
        migrations.AlterField(
            model_name='historicalrecibo',
            name='fecha_generacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='fecha_generacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='HistoricalFactura',
        ),
    ]
