# Generated by Django 4.1.7 on 2023-10-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_transaccion_factura_monto_historicalfactura_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaoffset',
            name='factura_offset_id',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
