# Generated by Django 4.1.7 on 2023-04-21 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s3_management', '0001_initial'),
        ('facturacion', '0007_remove_historicalfactura_history_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFactura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('fecha_generacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('n_factura', models.PositiveIntegerField(db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='facturacion.orden')),
                ('s3_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='s3_management.s3file')),
            ],
            options={
                'verbose_name': 'historical factura',
                'verbose_name_plural': 'historical facturas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('n_factura', models.PositiveIntegerField(db_index=True, unique=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.orden')),
                ('s3_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='s3_management.s3file')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
