# Generated by Django 4.1.7 on 2023-11-18 13:32

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file_management', '0005_historicaluploadedfile'),
        ('facturacion', '0007_facturaoffset_factura_offset_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacredito',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='notacredito',
            name='id',
        ),
        migrations.RemoveField(
            model_name='notadebito',
            name='id',
        ),
        migrations.AddField(
            model_name='notacredito',
            name='n_factura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notadebito',
            name='n_factura',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='n_notacredito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='n_notadebito',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='pago',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_de_debito', to='facturacion.pago'),
        ),
        migrations.CreateModel(
            name='NotasDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('n_notadebito', models.PositiveIntegerField(unique=True)),
                ('n_factura', models.PositiveIntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.orden')),
                ('s3_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploaded_file_management.uploadedfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotasCredito',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_generacion', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('n_factura', models.PositiveIntegerField(default=0)),
                ('n_notacredito', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturacion.orden')),
                ('s3_file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploaded_file_management.uploadedfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
