# Generated by Django 4.1.7 on 2023-11-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0008_remove_notacredito_factura_remove_notacredito_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notadebito',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='notadebito',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='notadebito',
            name='pago',
        ),
        migrations.RemoveField(
            model_name='notadebito',
            name='s3_file',
        ),
        migrations.DeleteModel(
            name='NotaCredito',
        ),
        migrations.DeleteModel(
            name='NotaDebito',
        ),
    ]
