# Generated by Django 4.1.7 on 2023-04-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3_management', '0001_initial'),
        ('facturacion', '0008_historicalfactura_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='s3_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='s3_management.s3file'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='s3_file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='s3_management.s3file'),
        ),
    ]
