# Generated by Django 4.1.7 on 2023-11-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_remove_notadebito_factura_remove_notadebito_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaoffset',
            name='factura_offset_id',
        ),
    ]
