# Generated by Django 4.1.7 on 2023-04-25 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0010_cambiousdbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiousdbs',
            name='bs_e',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=22),
        ),
    ]
