version: '3.9'

services:
  api:
    container_name: patolsimaapi
    image: patolsimaapi
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
    env_file:
      - .env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    restart: always
    env_file:
      - postgres_setup.env
    user: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  
volumes:
  postgres_data:

networks:
  backend:
  frontend:
