# Generated by Django 4.1.7 on 2023-05-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file_management', '0003_uploadedfile_content_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='informes_generados',
        ),
        migrations.AddField(
            model_name='historicalinforme',
            name='informes_generado',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='uploaded_file_management.uploadedfile'),
        ),
        migrations.AddField(
            model_name='informe',
            name='informes_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uploaded_file_management.uploadedfile'),
        ),
        migrations.DeleteModel(
            name='InformeGenerado',
        ),
    ]
