# Generated by Django 4.1.7 on 2023-04-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.PositiveIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
