# Generated by Django 4.1.7 on 2023-05-24 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_informe_informes_generados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoinmunostoquimica',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_inmunostoquimica', to='core.informe'),
        ),
    ]
