# Generated by Django 4.1.7 on 2023-03-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estudio_medicotratante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=5),
        ),
        migrations.AddField(
            model_name='estudio',
            name='tipo',
            field=models.CharField(choices=[('BIOPSIA', 'Biopsia'), ('CITOLOGIA', 'Citologia'), ('CITOLOGIA_ESPECIAL', 'Citologia Especial'), ('INMUNOSTOQUIMICA', 'Inmunostoquimica')], default='CITOLOGIA', max_length=18),
        ),
        migrations.AddField(
            model_name='historicalestudio',
            name='prioridad',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='BAJA', max_length=5),
        ),
        migrations.AddField(
            model_name='historicalestudio',
            name='tipo',
            field=models.CharField(choices=[('BIOPSIA', 'Biopsia'), ('CITOLOGIA', 'Citologia'), ('CITOLOGIA_ESPECIAL', 'Citologia Especial'), ('INMUNOSTOQUIMICA', 'Inmunostoquimica')], default='CITOLOGIA', max_length=18),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='ci',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
