# Generated by Django 4.1.7 on 2023-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_informe_estudio_estudio_asociado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=16, null=True),
        ),
    ]
