# Generated by Django 4.1.7 on 2023-06-02 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_historicalmedicotratante_ci_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatologo',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patologo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='patologo',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at', None)), fields=('user',), name='patologo_user_unique_when_not_deleted'),
        ),
    ]
