# Generated by Django 4.1.7 on 2023-04-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_estudio_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='tipo',
            field=models.CharField(choices=[('BIOPSIA', 'Biopsia'), ('CITOLOGIA_GINECOLOGICA', 'Citologia Ginecologica'), ('CITOLOGIA_ESPECIAL', 'Citologia Especial'), ('INMUNOSTOQUIMICA', 'Inmunostoquimica')], default='BIOPSIA', max_length=32),
        ),
        migrations.AlterField(
            model_name='historicalestudio',
            name='tipo',
            field=models.CharField(choices=[('BIOPSIA', 'Biopsia'), ('CITOLOGIA_GINECOLOGICA', 'Citologia Ginecologica'), ('CITOLOGIA_ESPECIAL', 'Citologia Especial'), ('INMUNOSTOQUIMICA', 'Inmunostoquimica')], default='BIOPSIA', max_length=32),
        ),
    ]
