# Generated by Django 4.1.7 on 2023-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicalpaciente_sexo_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patologo',
            name='ncomed',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
