# Generated by Django 4.1.7 on 2023-06-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicalpatologo_user_patologo_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='medico_tratante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.medicotratante'),
        ),
    ]
