# Generated by Django 4.1.7 on 2023-04-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_estudio_tipo_alter_historicalestudio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmuestra',
            name='estado',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('DESCRIPCION_MACROSCOPICA', 'Descripcion Macroscopica'), ('DESHIDRATACION', 'Deshidratacion'), ('INCLUSION_EN_PARAFINA', 'Inclusion En Parafina'), ('CORTE_MICROTOMO', 'Corte Microtomo'), ('COLORACION', 'Coloracion'), ('COLORACIONES_ESPECIALES', 'Coloraciones Especiales'), ('DIAGNOSTICO_MICROSCOPICO', 'Diagnostico Microscopico'), ('ALMACENAMIENTO', 'Almacenamiento'), ('DISPOSICION_DE_RESIDUOS', 'Disposicion De Residuos'), ('PERDIDA', 'Perdida')], default='RECIBIDA', max_length=32),
        ),
        migrations.AddField(
            model_name='muestra',
            name='estado',
            field=models.CharField(choices=[('RECIBIDA', 'Recibida'), ('DESCRIPCION_MACROSCOPICA', 'Descripcion Macroscopica'), ('DESHIDRATACION', 'Deshidratacion'), ('INCLUSION_EN_PARAFINA', 'Inclusion En Parafina'), ('CORTE_MICROTOMO', 'Corte Microtomo'), ('COLORACION', 'Coloracion'), ('COLORACIONES_ESPECIALES', 'Coloraciones Especiales'), ('DIAGNOSTICO_MICROSCOPICO', 'Diagnostico Microscopico'), ('ALMACENAMIENTO', 'Almacenamiento'), ('DISPOSICION_DE_RESIDUOS', 'Disposicion De Residuos'), ('PERDIDA', 'Perdida')], default='RECIBIDA', max_length=32),
        ),
    ]
