# Generated by Django 4.1.7 on 2023-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patologo_ncomed'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalestudio',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
