# Generated by Django 4.1.7 on 2023-06-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_estudio_medico_tratante'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudioCodigoOffset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_estudio', models.CharField(choices=[('BIOPSIA', 'Biopsia'), ('CITOLOGIA_GINECOLOGICA', 'Citologia Ginecologica'), ('CITOLOGIA_ESPECIAL', 'Citologia Especial'), ('INMUNOSTOQUIMICA', 'Inmunostoquimica')], default='BIOPSIA', max_length=32)),
                ('offset', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
