# Generated by Django 4.1.7 on 2023-06-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file_management', '0005_historicaluploadedfile'),
        ('core', '0007_estudiocodigooffset'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='images_for_rich_text',
            field=models.ManyToManyField(to='uploaded_file_management.uploadedfile'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='informes_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes_generados', to='uploaded_file_management.uploadedfile'),
        ),
    ]
