# Generated by Django 4.1.7 on 2023-04-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_historicalmuestra_estado_alter_muestra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='estudio_asociado',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalestudio',
            name='estudio_asociado',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
