# Generated by Django 4.1.7 on 2023-04-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s3_management', '0001_initial'),
        ('core', '0008_estudio_estudio_asociado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.estudio')),
                ('descripcion_macroscopica', models.TextField(blank=True, max_length=10240, null=True)),
                ('descripcion_microscopica', models.TextField(blank=True, max_length=10240, null=True)),
                ('diagnostico', models.TextField(blank=True, max_length=10240, null=True)),
                ('notas', models.TextField(blank=True, max_length=10240, null=True)),
                ('anexos', models.TextField(blank=True, max_length=10240, null=True)),
                ('bibliografia', models.TextField(blank=True, max_length=10240, null=True)),
                ('completado', models.BooleanField(default=False)),
                ('aprobado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoInmunostoquimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimiento', models.CharField(max_length=256)),
                ('reaccion', models.CharField(max_length=256)),
                ('diagnostico_observaciones', models.TextField(blank=True, max_length=1024, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.informe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformeGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.informe')),
                ('s3_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s3_management.s3file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='informes_generados',
            field=models.ManyToManyField(through='core.InformeGenerado', to='s3_management.s3file'),
        ),
    ]
