# Generated by Django 4.1.7 on 2023-07-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_informe_images_for_rich_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalestudio',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalinforme',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalmuestra',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informe',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='muestra',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
