# Generated by Django 4.1.7 on 2023-04-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_informe_resultadoinmunostoquimica_informegenerado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoinmunostoquimica',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultadod_inmunostoquimica', to='core.informe'),
        ),
    ]
