# Generated by Django 4.1.7 on 2023-08-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_estudio_archived_historicalestudio_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmedicotratante',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='medicotratante',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
    ]
