# Generated by Django 4.1.7 on 2023-05-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=512)),
                ('size', models.IntegerField()),
                ('s3_object_id', models.CharField(max_length=256)),
                ('s3_path', models.CharField(max_length=512)),
                ('s3_bucket_name', models.CharField(max_length=256)),
            ],
        ),
    ]
