# Generated by Django 4.1.7 on 2023-05-07 23:59

from django.db import migrations, models
import patolsima_api.apps.uploaded_file_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(db_index=True, default=patolsima_api.apps.uploaded_file_management.models.get_uuid_for_new_file, max_length=34, unique=True)),
                ('file_name', models.CharField(max_length=512)),
                ('local_filepath', models.CharField(blank=True, max_length=512, null=True)),
                ('storage_unit', models.CharField(choices=[('AWS_S3', 'Aws S3'), ('LOCAL_STORAGE', 'Local Storage')], default='LOCAL_STORAGE', max_length=16)),
                ('size', models.IntegerField()),
                ('object_key', models.CharField(blank=True, max_length=512, null=True)),
                ('bucket_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_time_requested', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
