# Generated by Django 4.1.7 on 2023-05-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploaded_file_management', '0002_alter_uploadedfile_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
